# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ELT con Python

on:
    workflow_dispatch:

jobs:
  extract:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: python ./scripts/extract.py
    - name: Save data for Load Job
      uses: actions/upload-artifact@v4
      with:
        name: amazon
        path: amazon_data.csv

  load:
      runs-on: ubuntu-latest
      permissions:                # Job-level permissions configuration starts here
        contents: write           # 'write' access to repository contents
        pull-requests: write
      needs: extract
      steps: 
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.10' 
              cache: 'pip' # caching pip dependencies
          - run: pip install -r requirements.txt
          - name: Download users data from Extract Job
            uses: actions/download-artifact@v4
            with:
              name: amazon
          - name: Subir datos
            run: python ./scripts/load.py
          - name: Save data for Load Job
            uses: actions/upload-artifact@v4
            with:
              name: Duckdb
              path: products_base.duckdb
          - uses: stefanzweifel/git-auto-commit-action@v5
            with:
              commit_message: Actualizacion del archivo
               
        
